### ISSUE TITLE
Infinity Loop

### ISSUE THREAD

**Issue by sthoni** [sthoni/gamejamaugust2024#2]
# To infinity!

Das erste Level ist geschafft, jetzt geht es weiter. Wenn man den Bahnhof verlässt und den Rand der Karte erreicht, wird eine neue Karte geladen.

* Bahnhof zufällig platziert
* Bahnhof zufällig groß
* Shop zufällige Items
* Umgebung zufällige Vegetation

## Todo

- [x] Bahnhof als Ressource
- [x] Level als Ressource
- [x] Train als Ressource
- [x] Level mit zufälligen Ressources erstellen können
- [x] Levelwechsel mit Abfahrt

## Bahnhof

Der Bahnhof hat eine gewisse y-Position und eine Mindestlänge. Am Anfang kann das Zielfenster sehr groß sein, sollte sich aber zunehmend verkleinern.
* y-Position
* Länge
* Sprite

## Level

Ein Level besteht aus einem Bahnhof mit Shop und einem Biome. Außerdem ist der Train auch auf der Strecke. Die Items für den Shop kommen aus einem ItemPool.

* Bahnhof
* Biom
* Train
* ItemPool

## Train

Der Train hat eine Geschwindigkeit, eine Engine und Items. Außerdem benötigt er ein Sprite

**Comment by sthoni** [comment]
Done. f73086b38660024ca8677a3a6a24207a4a178901
